server:
  port: 10002
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/login_user?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  application:
    name: user-service-provider
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
mybatis:
  mapper-locations: classpath:mybatis/*.xml